// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellSchedule.Models;

namespace WellSchedule.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180611153340_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("WellSchedule.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("From");

                    b.Property<string>("Title");

                    b.Property<DateTime>("To");

                    b.Property<int?>("WellId");

                    b.Property<int?>("WellId1");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId1");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("WellSchedule.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("WellSchedule.Models.Well", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("ScheduleId");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Well");
                });

            modelBuilder.Entity("WellSchedule.Models.Job", b =>
                {
                    b.HasOne("WellSchedule.Models.Well")
                        .WithMany("Jobs")
                        .HasForeignKey("WellId");

                    b.HasOne("WellSchedule.Models.Well")
                        .WithMany("JobsPool")
                        .HasForeignKey("WellId1");
                });

            modelBuilder.Entity("WellSchedule.Models.Well", b =>
                {
                    b.HasOne("WellSchedule.Models.Schedule")
                        .WithMany("Wells")
                        .HasForeignKey("ScheduleId");
                });
#pragma warning restore 612, 618
        }
    }
}
